### PR TITLE
Systray icon

### PR DESCRIPTION
**Pull request by spadino**
Added a SystemTray icon basic code.

### To-do list
- [x] DoubleClick minimize/restore
- [x] Window position, size and state persistence across runs
- [x] ContextMenu with:
  - [x] Show UCR 
  - [x]  Hide UCR 
  - [x]  Exit 

### For later
- [ ] Activate/De-Activate UCR from the systemtray
- [ ] Switch profile from the systemtray
- [ ] Access profile edit and device management from the systemtray
- [ ] Create some color variations to reflects some app states (loaded, active, inactive)
- [ ] Bind app states to change the systrayicon

---
Some minor code refactoring

### CODE REVIEW

**Comment by spadino** [comment]
@Snoothy, I removed the options form - which was intended to be called from the system tray - because now the UCR main window remember its state along its position and size. So, if someone want to start it minimized, just closing it while minimized (from the system tray menu) is enough.

**Comment by Snoothy** [comment]
Starting minimized should be an option which can be chosen not something which is just saved if you closed it while minimized

**Comment by spadino** [comment]
@Snoothy, yes I agree with you. However, I think that's better to merge the new works - on pr/12 and that branch to a common branch - before continue to work on the options form. I just disabled the entry, not actually removed it.

Unless you prefer I work on that before merge it. Let me know! ;)

**Comment by Snoothy** [comment]
@spadino update your branch (systrayicon) with the newest changes from the develop branch when #25 and #29 has been merged and open a new PR targeting develop

**Pull request closed without merging**
