### PR TITLE
AxisToAxisDamped plugin

### PR DESCRIPTION
**Pull request by swift502**
#37 #38 #39 
Sorry for the mess. I'm quite new to this. 🙂

### CODE REVIEW

**Comment by spadino** [comment]
Very interesting, @swift502! ;)

**Comment by swift502** [comment]
Should be useful in any driving game that allows for direct input. I made my own steering smoothing in Dirt Rally and it's night and day difference.

**Comment by spadino** [comment]
Indeed. I play space sim games, and I think that it could be great for such situation.

**Comment by evilC** [comment]
We are trying to minimize the number of plugins in core, else making changes can get cumbersome.  
We have a repo https://github.com/HidWizards/UCR-Plugins for plugin contributions, could you please submit it there?

**Comment by spadino** [comment]
@swift502

> We are trying to minimize the number of plugins in core, else making changes can get cumbersome.
We have a repo https://github.com/HidWizards/UCR-Plugins for plugin contributions, could you please submit it there?

**Comment by swift502** [comment]
I'll try to find some time but can't promise anything... :frowning_face: 
Been quite busy lately.

**Comment by spadino** [comment]
@swift502, we could copy your PR and push it, of course, but we can't do it "under your name". It's a very clever solution, and actually quite useful, so it would be a pity to not be credited for such interesting contribution. I hope you find a little time to push it to it's proper repository, as I use it a lot (in a custom local build). Then, we can polish it out... ;)

**Comment by swift502** [comment]
I'll try to do it on Friday. But if can't, I give you guys my full permission to do it for me. "Not being credited for it" is not really something I'm concerned about... :slightly_smiling_face:

**Comment by evilC** [comment]
The other reason for doing it as you is so that if we wonder "who wrote this?" we can easily tell...  
Only the person who wrote it knows what they intended - someone coming along later to maintain the code may not know what the original intent was, so by having your name against the code, we can ping you to ask ;)

**Comment by swift502** [comment]
Yeah sorry. I don't even use UCR anymore. I can't be bothered to setup the repos, test the functionality again, cleanup, commit and request a pull because of one file I wrote for a thing I don't even use anymore.

It's here as an interesting resource and anyone can use it if they think it might be useful to them.
The logic is literally 8 lines of code. I'm sure anyone will be able to figure out what it does.
And if not, that's fine.

Again sorry. 🙁

**Comment by swift502** [comment]
I realise it's ironic how instead of writing these comments I could've already done it, but I just can't bring myself to do it.
Guess I'm just really lazy and the joke's on me...

**Pull request closed without merging**
