### PR TITLE
Remapping an already created virtual output device

### PR DESCRIPTION
**Pull request by marcob2178**
Hi. Would it be possible to remap (assign keyboard buttons) to an already created virtual output device?

I do not want to create a new virtual output device , i would like to add keyboard inputs to thos already existe t virtual outpud device. How can i do that ?

Thanks!

### CODE REVIEW

**Comment by evilC** [comment]
Not sure why you used a Pull Request for this...  
Please be more specific.  
What kind of  device?  
What do you mean by "remap"? Do you mean alter how the OS sees the device, or do you simply mean taking some actions in response to the device (Whilst still allowing the OS to see the unchanged state of the device)? The latter is no problem, but the former potentially is.

**Comment by marcob2178** [comment]
Where can i contact you directly please?

**Comment by marcob2178** [comment]
Hi! 
What I am trying to do is this.
Virtual desktop or other programs , create a xbox 360 virtual controller in windows, to send inputs to steamvr, from buttoms clicked on a controller.
What i am trying to figure out is if i can get into this xbox 360 virtual controller created and add to it keyboard inputs.
So for example i hope i can send to steamvr not only the thumbstick input of the quest controller but also the wasd keystrokes that could be associated/mapped to the thumbstic.
Usually we can create our own virtual controller that to any button of a controller we can associate keystrokes of the keyboard (for example using ucr - universal control remapper- ).
How can i edit/add inputs to an already existing virtual controller?
Thanks!
    Il giovedì 11 luglio 2019, 05:28:58 GMT-4, Clive Galway <notifications@github.com> ha scritto:  
 
 
Not sure why you used a Pull Request for this...
Please be more specific.
What kind of device?
What do you mean by "remap"? Do you mean alter how the OS sees the device, or do you simply mean taking some actions in response to the device (Whilst still allowing the OS to see the unchanged state of the device)? The latter is no problem, but the former potentially is.

**Comment by evilC** [comment]
> Virtual desktop or other programs , create a xbox 360 virtual controller in windows  
Never heard of virtual desktop. The only app I know of which does this is Parsec  
Really not understanding the use-case here, `steamvr` = virtual reality? What would be the point in sending remote input to a VR app?

> Where can i contact you directly please?

The Discord channel is linked in the docs.  https://github.com/Snoothy/UCR#support--discussion--feedback

**Comment by Snoothy** [comment]
Please use Discord for questions

**Pull request closed without merging**
